name: 이슈 등록
description: 발생한 이슈와 필요한 작업 내용을 작성해주세요.
title: "[이슈]: "
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🐞 이슈 내용  
        아래에 발생한 이슈의 상세한 내용을 작성해주세요.

  - type: textarea
    id: issue-description
    attributes:
      label: 이슈 내용
      description: 발생한 이슈를 가능한 한 구체적으로 설명해주세요.
      placeholder: |
        예시:
        - 로그인 시 빈 화면이 출력됩니다.
        - 특정 버튼을 눌러도 반응이 없습니다.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### ✅ 요청 사항  
        아래 체크박스 항목에 필요한 작업 내용을 작성해주세요.

  - type: textarea
    id: request-tasks
    attributes:
      label: 요청 작업
      description: 해결을 위해 필요한 작업을 항목별로 정리해주세요.
      placeholder: |
        - [ ] 로그인 오류 해결
        - [ ] 버튼 클릭 이벤트 연결
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 👤 담당자  
        담당 파트와 GitHub ID를 아래 형식으로 작성해주세요.

  - type: textarea
    id: assignee
    attributes:
      label: 담당자
      description: (파트) : (@GitHub ID) 형식으로 작성
      placeholder: |
        - Frontend : @alice
        - Backend : @bob
    validations:
      required: false
